CREATE TABLE IF NOT EXISTS documents (
    id INT AUTO_INCREMENT PRIMARY KEY,
    documentPath VARCHAR(255) NOT NULL,
    documentName VARCHAR(255) DEFAULT NULL,
    user_id INT DEFAULT NULL,
    memberId INT DEFAULT NULL,
    uploadDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_documents_users FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_documents_members FOREIGN KEY (memberId) REFERENCES members(id) ON DELETE CASCADE ON UPDATE CASCADE
);
